name: foodcast_2022
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.11.5
    - pip: 
        - pandas==2.0.3
        - numpy==1.24.3
        - scipy==1.11.1
        - matplotlib==3.7.2
        - seaborn==0.12.2
        - scikit-learn==1.3.0
